create or replace view fnd.sp_pen_dog_v as
with w_pen_dog as (
  select 'SP_PEN_DOG' source_table,
         sp.nom_vkl, 
         sp.nom_ips, 
         sp.fio, 
         cast(null as date) data_arh,
         sp.data_otkr, 
         sp.ssylka, 
         sp.data_nach_vypl, 
         sp.data_okon_vypl, 
         sp.razm_pen, 
         sp.delta_pen, 
         sp.delta_pere, 
         sp.summa, 
         sp.summa_u, 
         sp.summa_c, 
         sp.data_dog, 
         sp.nom_dog, 
         sp.flag, 
         sp.kod_oper, 
         sp.flg_admin, 
         sp.data, 
         sp.sopr_oper, 
         sp.nom_pz, 
         sp.type_dog, 
         sp.data_uvoln, 
         sp.shema_dog, 
         sp.data_perevoda_5_cx,
         sp.id_period_payment, 
         sp.id_letter, 
         sp.ref_kodinsz, 
         sp.kod_insz, 
         sp.summa_perevoda_5_cx
  from   sp_pen_dog sp
  union all
  select 'SP_PEN_DOG_ARH' source_table,
         spa.nom_vkl, 
         spa.nom_ips, 
         spa.fio, 
         spa.data_arh,
         spa.data_otkr, 
         spa.ssylka, 
         spa.data_nach_vypl, 
         spa.data_okon_vypl, 
         spa.razm_pen, 
         spa.delta_pen, 
         spa.delta_pere, 
         spa.summa, 
         spa.summa_u, 
         spa.summa_c, 
         spa.data_dog, 
         spa.nom_dog, 
         spa.flag, 
         spa.kod_oper, 
         spa.flg_admin, 
         spa.data, 
         spa.sopr_oper, 
         spa.nom_pz, 
         spa.type_dog, 
         spa.data_uvoln, 
         spa.shema_dog, 
         spa.data_perevoda_5_cx,
         spa.id_period_payment, 
         spa.id_letter, 
         spa.ref_kodinsz, 
         spa.kod_insz, 
         spa.summa_perevoda_5_cx
  from   sp_pen_dog_arh spa
)
select sp.source_table,
       sp.nom_vkl, 
       sp.nom_ips, 
       sp.fio, 
       sp.data_arh,
       sp.data_otkr, 
       sp.ssylka, 
       sp.data_nach_vypl, 
       sp.data_okon_vypl, 
       lead(sp.data_nach_vypl - 1) over(partition by sp.ssylka order by sp.data_nach_vypl) data_okon_vypl_next,
       sp.razm_pen, 
       sp.delta_pen, 
       sp.delta_pere, 
       sp.summa, 
       sp.summa_u, 
       sp.summa_c, 
       sp.data_dog, 
       sp.nom_dog, 
       sp.flag, 
       sp.kod_oper, 
       sp.flg_admin, 
       sp.data, 
       sp.sopr_oper, 
       sp.nom_pz, 
       sp.type_dog, 
       sp.data_uvoln, 
       sp.shema_dog, 
       sp.data_perevoda_5_cx,
       sp.id_period_payment, 
       sp.id_letter, 
       sp.ref_kodinsz, 
       sp.kod_insz, 
       sp.summa_perevoda_5_cx
from   w_pen_dog sp
where  sp.shema_dog <> 7
--and    sp.nom_vkl <> 1001
/
grant select on sp_pen_dog_v to gazfond
/
