CREATE DATABASE LINK weekly_vbz_5
CONNECT TO gazfond IDENTIFIED BY gazfond
USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))) (CONNECT_DATA = (SERVER=dedicated)(SERVICE_NAME=weekly_vbz_5)))'
/
