merge into transform_banks tbs
using (select 100000 + sbr.kod_rbank as id,
              sbr.kod_rbank,
              sbr.kod_rbank as fk_bank_account,
              sbr.nazv_rb as title,
              sbr.mfo_pp as bic,
              sbr.r_schet_pp as current_account,
              sbr.nom_osb_rb as sberbank_dept_num,
              sbr.klir_schet as clearing_account,
              sbr.voznagr_bank as bank_commission,
              sbr.nal_nds as nds,
              sbr.ident_k,
              sbr.ident_g,
              sbr.name_file as filename,
              sbr.nazn_plat as payment_template,
              sbr.kontakt as contact,
              sbr.group_pp,
              sbr.group_spisok,
              sbr.group_ot,
              sbr.post as group_post,
              sbr.category_ot,
              sbr.mnemokod_pp as account_spec,
              substr(sbr.inn, 1, 9) as inn,
              sbr.voznagr_max as max_reward,
              sbr.country as fk_country_code,
              sbr.region as fk_region_code,
              1 as fond,
              (select max(kod_open)
               from   fnd.sp_bank_dop_office dof
               where  dof.kod_rbank = sbr.kod_rbank) as isactive,
              sbr.modified_date
       from   fnd.sp_bank_region sbr) sq
on (tbs.id = sq.id)
when matched then
  update
  set    tbs.title             = sq.title,
         tbs.bic               = sq.bic,
         tbs.current_account   = sq.current_account,
         tbs.sberbank_dept_num = sq.sberbank_dept_num,
         tbs.clearing_account  = sq.clearing_account,
         tbs.nds               = sq.nds,
         tbs.ident_k           = sq.ident_k,
         tbs.ident_g           = sq.ident_g,
         tbs.filename          = sq.filename,
         tbs.payment_template  = sq.payment_template,
         tbs.contact           = sq.contact,
         tbs.group_pp          = sq.group_pp,
         tbs.group_spisok      = sq.group_spisok,
         tbs.group_ot          = sq.group_ot,
         tbs.group_post        = sq.group_post,
         tbs.category_ot       = sq.category_ot,
         tbs.account_spec      = sq.account_spec,
         tbs.inn               = sq.inn,
         tbs.fk_country_code   = sq.fk_country_code,
         tbs.fk_region_code    = sq.fk_region_code,
         tbs.max_reward        = sq.max_reward,
         tbs.isactive          = abs(sq.isactive)
when not matched then
  insert
    (id,
     kod_rbank,
     fk_bank_account,
     title,
     bic,
     current_account,
     sberbank_dept_num,
     clearing_account,
     bank_commission,
     nds,
     ident_k,
     ident_g,
     filename,
     payment_template,
     contact,
     group_pp,
     group_spisok,
     group_ot,
     group_post,
     category_ot,
     account_spec,
     inn,
     fk_country_code,
     fk_region_code,
     max_reward,
     fond,
     isactive,
     modified_date)
  values
    (sq.id,
     sq.kod_rbank,
     sq.kod_rbank,
     sq.title,
     sq.bic,
     sq.current_account,
     sq.sberbank_dept_num,
     sq.clearing_account,
     sq.bank_commission,
     sq.nds,
     sq.ident_k,
     sq.ident_g,
     sq.filename,
     sq.payment_template,
     sq.contact,
     sq.group_pp,
     sq.group_spisok,
     sq.group_ot,
     sq.group_post,
     sq.category_ot,
     sq.account_spec,
     sq.inn,
     sq.fk_country_code,
     sq.fk_region_code,
     sq.max_reward,
     sq.fond,
     abs(sq.isactive),
     sq.modified_date
    )
/
merge into transform_banks tbs
using (select kod_bank      as id,
              kod_rbank,
              kod_do,
              nazv_do,
              kod_open      as isactive,
              kontakt,
              nazv_old,
              gorod,
              1             as fond,
              kod_rbank     as fk_bank_office,
              kod_bank      as kod_bank,
              modified_date
       from   fnd.sp_bank_dop_office) sq
on (tbs.id = sq.id)
when matched then
  update
  set    tbs.title     = sq.nazv_do,
         tbs.kod_do    = sq.kod_do,
         tbs.title_old = sq.nazv_old,
         tbs.isactive  = sq.isactive,
         tbs.contact   = sq.kontakt,
         tbs.address   = sq.gorod
when not matched then
  insert
    (id,
     kod_rbank,
     title,
     title_old,
     isactive,
     contact,
     address,
     fond,
     fk_bank_office,
     kod_bank,
     modified_date)
  values
    (sq.id,
     sq.kod_rbank,
     sq.nazv_do,
     sq.nazv_old,
     abs(sq.isactive),
     sq.kontakt,
     sq.gorod,
     sq.fond,
     sq.fk_bank_office,
     sq.kod_bank,
     sq.modified_date)
/
